name: Github Release and NPM Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          release-type: node
  
  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created }}

    name: NPM Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}