on:
  push:
    branches:
      - main

permissions:
  contents: write # to create release commit (googleapis/release-please-action)
  pull-requests: write # to create release PR (googleapis/release-please-action)

name: release-please

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
  
  publish:
    needs: release
    if: ${{ needs.release.outputs.release_created }}

    name: NPM Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}